### ISSUE TITLE
‘yolo3_darknet53_voc’ net can not work with input image size is large as (1280, 720)

### ISSUE THREAD

**Issue by jeremycheong** [dmlc/gluon-cv#1028]
I use `yolo3_darknet53_voc` net test a video file, the image i has resized to (1280, 720), but it also does not work, the error info:
```
mxnet.base.MXNetError: [17:55:49] src/operator/tensor/./matrix_op-inl.h:1314: Check failed: ishape[axis] >= from_shape[axis] (128 vs. 160) : Slice axis 3 with size 160exceeds limit of input with size 128
```
and i found some clues in the class 'YOLOOutputV3' in `yolo3.py` file, maybe i should define the param 'alloc_size' a little bigger which default is (128, 128).

i found the api doc and did not find the function i can use, when i change the default param from 128 to 256 in the class '__init__' function it also did not work with error info:
```
AssertionError: Failed loading Parameter 'yolov30_yolooutputv30_offset_0' from saved params: shape incompatible expected (1, 1, 256, 256, 2) vs saved (1, 1, 128, 128, 2)
```

I just want to use it with the large input image, how can i do next?

**Comment by PawelFaron** [comment]
Same here

**Comment by Jerryzcn** [comment]
the model is trained with alloc_size 128,128, so the parameters shape won't match if you change it 256. You can manually change it inside the parameter i suppose, or train a new model

**Comment by MSDimos** [comment]
I figured it out. 
This is because that this model generates anchors with shape (batch_size, num_filter, feature_h, feature_w), and `yolo3_darknet53_voc` set `alloc_size` as `(128, 128)` which means that `feature_h` and `feature_w` should less than or equal to `128`. In other words, the maximium width and height of input image should less than or equal to `128 * 8=1024`. Just resize the image size which you input.
