### ISSUE TITLE
The accuracy of i3d_resnet50_v1_ucf101 trained on Imagenet and K400

### ISSUE THREAD

**Issue by chenyihang1993** [dmlc/gluon-cv#1037]
Hi， I tested the i3d_resnet50_v1_ucf101 trained on Imagenet and K400 on UCF101，but the accuracy is 93.4 while the accuracy posted is 95.4. The command is 
```
python3 test_recognizer.py --dataset ucf101 --data-dir /home/cyh/.mxnet/datasets/ucf101/rawframes --val-list /home/cyh/.mxnet/datasets/ucf101/ucfTrainTestlist/ucf101_val_split_1_rawframes.txt --model i3d_resnet50_v1_ucf101 --use-pretrained --num-classes 101 --mode hybrid --dtype float32 --batch-size 4 --num-gpus 1 --num-data-workers 12 --new-height 256 --new-width 340 --new-length 32 --new-step 2 --input-size 224 --log-interval 10
```
Please tell me how to solve it. THX.

**Comment by bryanyzhu** [comment]
Hi, looks like you are using a single crop for evaluation, so 93.4 is already a decent number. 

To achieve 95.4, please set another two flags, 
```
--three-crop
--num_segments 10
```
Because usually people perform such 30-view evaluation strategy for I3D models to report their performance. You can find more details in this paper, https://arxiv.org/abs/1711.07971

**Comment by bryanyzhu** [comment]
@chenyihang1993 Just want to check, have you used the extra flags and get the correct number? Thank you.

**Comment by bryanyzhu** [comment]
@chenyihang1993  Close the issue due to inactivity. You can reopen it if you can't reproduce the 95.4 number.
