### ISSUE TITLE
Error on mxnet/gluon: after upgrade the mxnet-cu100 and gluoncv,then run script "train_faster_rcnn.py"

### ISSUE THREAD

**Issue by HuFBH** [dmlc/gluon-cv#1066]
My virtual environment is broken and then I create a new virtual environment named  "huf_mx" as  following.

![image](https://user-images.githubusercontent.com/47581857/69799144-ac21ea00-120d-11ea-8ecb-5367dc9a7fce.png)

Trying to run script "train_faster_rcnn.py" on spyder IDE, I get the error.
As shown in the image, there are some problem on mxnet/gluon, or maybe gluoncv either.

How to fix it, installing another mxnet?
I have tried 1.4.0,but not work.

thx a lot.

**Comment by HuFBH** [comment]
install gluoncv==0.4.0
run the script  "train_faster_rcnn.py" of gluoncv(0.4.0),this can be an alternative.

**Comment by bryanyzhu** [comment]
This is because the script doesn't match with gluoncv version. Similar issue has been resolved in 
https://github.com/dmlc/gluon-cv/issues/1002

My suggestion would be to install the latest gluoncv (either install the nightly version or build from source using master branch). Or you can downgrade the script to gluoncv 0.4.0 as HuFBH suggested.

**Comment by HuFBH** [comment]
> This is because the script doesn't match with gluoncv version. Similar issue has been resolved in
> #1002
> 
> My suggestion would be to install the latest gluoncv (either install the nightly version or build from source using master branch). Or you can downgrade the script to gluoncv 0.4.0 as HuFBH suggested.

thanks a lot.
