### ISSUE TITLE
ValueError: "mobile_pose_mobilenetv3_small" is not among the following model list:

### ISSUE THREAD

**Issue by zhangyunming** [dmlc/gluon-cv#1102]
1. when i  train the mobile_pose_mobilenetv3_small, it appears :                                              
 ValueError: "mobile_pose_mobilenetv3_small" is not among the following model list, my gluoncv is 0.5

2. when i download the params and json,yolo3_mobilenet0.25_coco is not the weights
net = gcv.model_zoo.get_model('yolo3_mobilenet0.25_coco', pretrained=True)
Model file is not found. Downloading.
Downloading C:\Users\zhangyunming-os\.mxnet\models\yolo3_mobilenet1.0_coco-66dbbae6.zip

**Comment by bryanyzhu** [comment]
Hi,

1. `mobile_pose_mobilenetv3_small ` is available in master branch, not in 0.5.0. That's why it shows the valueError. If you want to use this model, please build from source or install the nightly version of gluoncv.

2. The model weight of `yolo3_mobilenet0.25_coco ` is not in the model zoo yet. @zhreshold Is there a plan to add this model to model store? Thank you.

**Comment by zhangyunming** [comment]
hi，@bryanyzhu ，

thank you very much, now  i have get the params and json of mobile_pose_mobilenetv3_small with building gluon of source.  but there is not a weight of detector with basenet of mobile0.25. nither ssd nor yolo3. must train it myself?

**Comment by zhreshold** [comment]
@zhangyunming  The smallest detection models are with 1.0 factor not 0.25 so far. It's planned to provide pretrained weights but there's ETA yet.

**Comment by zhangyunming** [comment]
@zhreshold ,thank you so much , if i want to train a sameple or mobile  pose model that based with mobile0.25 , how can i to do that.
