### ISSUE TITLE
deeplab_v3b_plus_wideresnet_citys training script and log file is missing

### ISSUE THREAD

**Issue by ShoufaChen** [dmlc/gluon-cv#1121]
For semantic segmentation, `deeplab_v3b_plus_wideresnet_citys`  on cityscapes dataset,  the training script and log file is missing.

https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/segmentation/deeplab_v3b_plus_wideresnet_citys.sh

https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/segmentation/deeplab_v3b_plus_wideresnet_citys.log

**Comment by bryanyzhu** [comment]
In order to fully reproduce this model, we need to first pre-train the model on Mapillary dataset, which GluonCV doesn't support at this moment. I am working on this and will provide them at a later time. If you want to see the training command now, you can check [here](https://github.com/NVIDIA/semantic-segmentation/blob/master/scripts/train_cityscapes_WideResNet38.sh) and this [repo](https://github.com/NVIDIA/semantic-segmentation) for more information.
