### ISSUE TITLE
Training slowfast: computer's memory usage increased

### ISSUE THREAD

**Issue by chenyihang1993** [dmlc/gluon-cv#1208]
When I used slowfast to train my own dataset, I found that the computer's memory usage increased with time. Is this normal? Looking forward for your reply.

**Comment by bryanyzhu** [comment]
Yes, it is normal because data loading is very heavy for video model training. Besides, for MXNet, we use async compute, details can be found here, 
https://d2l.ai/chapter_computational-performance/async-computation.html

Using async can speed up training, but it may cause the problem that input loaded too fast, and can't be deleted in time. So the CPU memory usage will increase with time.

If you have a limited CPU memory, you can manually perform garbage collection more frequently like what I did here,

https://github.com/dmlc/gluon-cv/blob/master/scripts/action-recognition/test_recognizer.py#L269-L271

**Comment by chenyihang1993** [comment]
OK, I got it. THX.
