### ISSUE TITLE
Using slowfast_4x16_resnet50_custom pretrained model setting pretrained True seems not to be effective. 

### ISSUE THREAD

**Issue by chenyihang1993** [dmlc/gluon-cv#1219]
I want to use slowfast_4x16_resnet50_custom pretrained model and set the paramter pretrained True,   but the pretrained parameters seems not to be loaded. The part of the code is https://github.com/dmlc/gluon-cv/blob/master/gluoncv/model_zoo/action_recognition/slowfast.py#L916-L919

**Comment by bryanyzhu** [comment]
You need to set `use_kinetics_pretrain ` to True, and `pretrained ` to False. 

Because for custom model, there is pretrained weights you can directly use. The number of classes is different for each dataset. You can only choose to use weights that pre-trained on other datasets, such as Kinetics400.

**Comment by chenyihang1993** [comment]
What is the pretrained weights of custom model I can directly use?

**Comment by bryanyzhu** [comment]
Right now, if you set use_kinetics_pretrain=True, you are using a kinetics400 pretrained weights, only the last dense layer is newly initialized because the number of classes is different from datasets to datasets.

If you didn't specify use_kinetics_pretrain to True, you are by default using an ImageNet pretrained weights.

**Comment by bryanyzhu** [comment]
Close the issue for now. If you have other questions, feel free to re-open it or open a new issue. Thank you.
