### ISSUE TITLE
[Object Tracking] Handling Frame Exit

### ISSUE THREAD

**Issue by HieronymusLex** [dmlc/gluon-cv#1223]
I’m curious if there are any recommendations for how to perform object reidentification when using SiamRPN for SOT? My scenario is when the tracked object leaves the view in one frame causing the best_score to drop below some threshold, then they reenter in a subsequent frame, entering from a different location to their exit point.

**Comment by bryanyzhu** [comment]
I'm not familiar with this topic, but I think your scenario is more like ReID than tracking. Current Siamese-based tracking method can't handle such object missing and re-appear very well. You may want to check multi-object tracking literature because they consider ID switch, which is more like ReID.

**Comment by HieronymusLex** [comment]
thanks @bryanyzhu - will look into that and closing this issue. 

btw do you know if there's any plans to develop https://github.com/dmlc/gluon-cv/tree/master/scripts/re-id/baseline a bit further e.g. add a pre-trained model to the model zoo and a tutorial? If I get anywhere with it I'm happy to create a PR

**Comment by bryanyzhu** [comment]
Hi, @hetong007 Do we have plan to do this, adding a pre-trained model and tutorial for ReID? Thank you.

**Comment by hetong007** [comment]
@HieronymusLex Currently ReID is not our prioritized task, so your contribution is welcome.
