### ISSUE TITLE
'data_aug' keyword error in inference.py for action recognition application under Sagemaker 

### ISSUE THREAD

**Issue by oilpig** [dmlc/gluon-cv#1311]
Hi, I am testing the inference.py in Sagemaker (condo_mxnet_p36). It seems that it doesn't work in the initial stage. I followed this tutorial, https://gluon-cv.mxnet.io/build/examples_action_recognition/demo_custom.html
<img width="1011" alt="Screen Shot 2020-05-20 at 10 12 24 AM" src="https://user-images.githubusercontent.com/4879237/82397292-b4533780-9a82-11ea-91f5-41ee11c005a8.png">
The version of MXNet is 1.6.0 and GluonCV is 0.7.0
<img width="247" alt="Screen Shot 2020-05-20 at 10 15 36 AM" src="https://user-images.githubusercontent.com/4879237/82397358-dea4f500-9a82-11ea-89c7-5bfc2515be08.png">

**Comment by bryanyzhu** [comment]
The `data_aug` argument is added after GluonCV 0.7.0 release. The error is because you use the most recent `inference.py` in the master branch, but use an older gluoncv codebase.

Two options here,

1. Use master branch GluonCV instead of 0.7.0. You can do this by 

```
git clone https://github.com/dmlc/gluon-cv.git
cd gluon-cv
pip install -e .
```

In this way, you are using the most recent gluoncv codebase, as well as the most recent `inference.py`. 

2. Downgrade your `inference.py` file before this commit https://github.com/dmlc/gluon-cv/commit/8dcecebdfaad982f1815b6b87f49c17e03aac1b6

In this way, the `inference.py` matches with gluoncv 0.7.0.

**Comment by oilpig** [comment]
Thanks, it works for me!
