### ISSUE TITLE
License of pre-trained i3dresnet50 with kinetics400/ucf101

### ISSUE THREAD

**Issue by hasanp87** [dmlc/gluon-cv#1345]
What is the license for pre-trained models like https://gluon-cv.mxnet.io/_modules/gluoncv/model_zoo/action_recognition/i3d_resnet.html#i3d_resnet50_v1_kinetics400

What is the license for datasets like UCF101 which are sourced from youtube but do not explicitly mention a license https://www.crcv.ucf.edu/data/UCF101.php

**Comment by bryanyzhu** [comment]
I think in terms of I3D model license, it should follow the Apache 2.0 license in the original repo, https://github.com/deepmind/kinetics-i3d/blob/master/LICENSE

But for datasets, I'm not sure. This is a big problem in video research nowadays, because most datasets are crawled from YouTube. 

@zhreshold Any comments on the license thing? Thank you.

**Comment by zhreshold** [comment]
The code for training these models are under Apache 2.0 and the pre-trained weights are again under the same license as it's trained and provided by GluonCV. 

AFAIK, the license of the derived model weights has nothing to do with it's original training dataset, correct me if I am wrong.

**Comment by bryanyzhu** [comment]
Close the issue for now. Feel free to re-open it with more questions, thank you.
