### ISSUE TITLE
predict action recognition models on continuous video such as webcam streams...

### ISSUE THREAD

**Issue by alighofrani95** [dmlc/gluon-cv#1351]
Hi dear gcv developer
I really enjoyed the action recognition implementation on gcv

just one thing
How can I predict models such as i3d-nl and slowFast on continuous video such as webcam streams

thanks a lot

**Comment by bryanyzhu** [comment]
Hi, one simple way is to follow this tutorial, https://gluon-cv.mxnet.io/build/examples_action_recognition/demo_i3d_kinetics400.html

Instead of reading the video offline, you can use cv2 to read webcam streams and save the frames to a queue. Once the queue has 32 frames, you perform one inference. After that, you will enqueue new frames and deque the oldest frames to perform online prediction. 

For more details, you can refer to ECO (ECCV 2018) paper to see how people perform online video prediction. https://arxiv.org/pdf/1804.09066.pdf

**Comment by bryanyzhu** [comment]
Closing the issue. Feel free to reopen it if new things come up.

**Comment by bernalou** [comment]
TypeError: Don't know how to handle type <class 'list'> This is the error when i tried save the frames in a list. How i can save the frames in a queue ?
Do you have a code example ?
Thanks

**Comment by bryanyzhu** [comment]
Use a simple list should do the job. 

```
frames = []
cap = cv2.VideoCapture(0)
num_frames = 32

for i in range(num_frames):
    ret, frame = cap.read()
    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    frames.append(frame)
```

I didn't run this code snippet, but should be something like this.
