### ISSUE TITLE
pretrained ICNet export error

### ISSUE THREAD

**Issue by get-user-name** [dmlc/gluon-cv#1382]
Hi.
When I tried to export pre-trained ICNet, an error occurred.
How can I export it??

```
>>> import gluoncv as gcv
>>> from gluoncv.utils import export_block
>>> net = gcv.model_zoo.get_model('icnet_resnet50_mhpv1', pretrained=True)
>>> export_block('icnet_resnet50_mhpv1', net, preprocess=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/Codes/test_toolkit_comparison/venv/lib/python3.7/site-packages/gluoncv/utils/export_helper.py", line 153, in export_block
    raise RuntimeError(str(last_exception).splitlines()[0])
RuntimeError: Error in operator icnet0_cascadefeaturefusion0__plus0: [18:09:44] src/operator/contrib/../elemwise_op_common.h:135: Check failed: assign(&dattr, vec.at(i)): Incompatible attr in node icnet0_cascadefeaturefusion0__plus0 at 1-th input: expected [1,128,60,60], got [1,128,75,75]
```

**Comment by Aktcob** [comment]
input: expected [1,128,60,60], got [1,128,75,75]

check the shape of tensor

**Comment by bryanyzhu** [comment]
@KuangHaofei Could you take a look at this? Thank you.

**Comment by Aktcob** [comment]
import gluoncv as gcv
from gluoncv.utils import export_block
net = gcv.model_zoo.get_model('icnet_resnet50_mhpv1', pretrained=False, pretrained_base=False)
net.initialize(force_reinit=True)
img = nd.zeros([1,3,320,320])
print (net.demo(img).shape)
export_block('icnet_resnet50_mhpv1', net, preprocess=True)

No error!    When predict img, pls use net.demo, not the default function hybrid_forward @bryanyzhu @get-user-name 
ps: pretrained False, cause download pretrained model slowly since firewall

**Comment by get-user-name** [comment]
It works!! Thanks you~

---
I have a question.
Why isn't the code below working?

```
import mxnet
import gluoncv as gcv
from gluoncv.utils import export_block
net = gcv.model_zoo.get_model('icnet_resnet50_mhpv1', pretrained=False, pretrained_base=False)
net.initialize(force_reinit=True)

#### without these two lines ####
# img = mxnet.nd.zeros([1,3,320,320]) 
# print (net.demo(img).shape)

export_block('test',net,preprocess=True)
```

**Comment by Aktcob** [comment]
since I reinit the model and the shape of some layers parameters should be deferred. (like Convolution, sometimes, we do not need init the in_channels of Convolution layers since the shape of those can be deferred.)

So, u must test one fake image and the model can determine the shape of some layers. Also, u can set pretrained as True, u do not need test fake image.
