### ISSUE TITLE
Feature extraction using SlowFast

### ISSUE THREAD

**Issue by amil-rp-work** [dmlc/gluon-cv#1478]
I am trying to follow the tutorial mentioned here [Gluon CV - Feature extraction of videos](https://gluon-cv.mxnet.io/build/examples_action_recognition/feat_custom.html) and using the SlowFast network for extraction since it has achieved the best performance in the Kinetics400 dataset. 
I created a file with paths of `.mp4` files and the total frames and index.
 I used the following code to extract features
`python3 feat_extract.py --data-list ./file_paths_gluon.txt --model slowfast_8x8_resnet101_kinetics400 --save-dir ./slow_fast --slowfast --slow-temporal-stride 16 --fast-temporal-stride 2`
However I am facing the following error
`MXNetError: Check failed: dim_size_is_known(d[i]): Shape dim size must be known, while received -1`
Any help with this ?

As a side note the videos are
- 16:9 aspect ration, 720p videos shot at 60 frames per second

**Comment by bryanyzhu** [comment]
Hi, sorry for the late response. Can you please try to set `--slow-temporal-stride 8` and see if it works? Since you are using `slowfast_8x8_resnet101_kinetics400 ` model, it requires different input dimension. 

You can check the training command line of `slowfast_8x8_resnet101_kinetics400` at [here](https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/action_recognition/kinetics400/slowfast_8x8_resnet101_kinetics400.sh).

**Comment by starsholic** [comment]
also meet this problem in slowfast_4*16 and 8*8 model
