### ISSUE TITLE
In action recognition, why there are many mismatches between the top-1 in the tables and in the log files

### ISSUE THREAD

**Issue by saghiralfasly** [dmlc/gluon-cv#1606]
For action recognition, I am wondering why there are many mismatches between the reported ones in the tables and in the log files here: [https://cv.gluon.ai/model_zoo/action_recognition.html](url)
for example: on kinetics400 i3d_resnet50_v1_kinetics400 reported Top-1 74.0 in the table whereas in the log file the best results achieved is Top-1 66.66.

here are some more examples:
Model+Dataset                                        Top-1 in table                        Top-1 in the log file
slowfast_8x8_resnet101_kinetics400            77.2                                           69.5
i3d_resnet50_v1_ucf101                                83.9                                           80.3
i3d_resnet50_v1_hmdb51                              48.5                                           46.3
resnet50_v1b_sthsthv2                                   35.5                                           34.8

Thank you in advance

**Comment by bryanyzhu** [comment]
Hi, in the log files, we report single-clip accuracy. To be specific, we pick a video clip from the middle of each video, do the network forward and get prediction. Since we are only using one clip instead of the whole video, the accuracy is lower. 

However, in the table, we follow the evaluation convention termed 30-view test. To be specific, we pick 10 video clips uniformly from each video, do the network forward for each clip and average the prediction scores from the 10 clips. Since we are using more information (seeing more video frames), the performance will be higher. Usually this multiple-clip testing scheme will be 5% to 10% better than just using one clip, depending on the network.

The reason we use the single-clip evaluation score during training (in the log files) is because we don't want to slow down the training. A single-clip evaluation only takes 5 minutes but a 10-clip evaluation takes about 2 hour. Hope this clarifies.

**Comment by saghiralfasly** [comment]
Thanks for your reply.
I have tried to use the test_recognizer.py for doing the same settings you mentioned with the parameters --ten-crop. but whenever I evaluate using these settings I get 5% to 10% less accuracy. the exact opposite of what you said. May you provide us a sample of the shell script you used for evaluating any dataset. 

Thank you in advance.

**Comment by bryanyzhu** [comment]
Here is one for I3D, the rest are the same. The essential part is to set `--num _segments 10` and `--three-crop`, this will make the standard 30-view testing scheme.

```
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python ./scripts/action-recognition/test_recognizer.py \
  --dataset kinetics400 \
  --data-dir /home/ubuntu/data/kinetics400/val_256 \
  --val-list /home/ubuntu/data/kinetics400/k400_val.txt \
  --model i3d_resnet50_v1_kinetics400 \
  --use-pretrained \
  --video-loader \
  --num-classes 400 \
  --mode hybrid \
  --dtype float32 \
  --prefetch-ratio 1.0 \
  --batch-size 1 \
  --num-gpus 8 \
  --num-data-workers 32 \
  --new-height 256 \
  --new-width 340 \
  --new-length 32 \
  --new-step 2 \
  --input-size 224 \
  --three-crop \
  --num-segments 10 \
  --log-interval 10
```

**Comment by saghiralfasly** [comment]
Hi @bryanyzhu , thank you very much for your reply. I used the provided sh script. it shows better results with `--num _segments 10` and  `--three-crop`.
However, I have some queries here:
 
1. when I run the same script you provided I got the following error:

> """
Traceback (most recent call last):
  File "/home/alfasly/.conda/envs/torch/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/alfasly/.conda/envs/torch/lib/python3.7/site-packages/mxnet/gluon/data/dataloader.py", line 450, in _worker_fn
    batch = batchify_fn([_worker_dataset[i] for i in samples])
  File "/home/alfasly/.conda/envs/torch/lib/python3.7/site-packages/mxnet/gluon/data/dataloader.py", line 450, in <listcomp>
    batch = batchify_fn([_worker_dataset[i] for i in samples])
  File "/home/alfasly/.local/lib/python3.7/site-packages/gluoncv-0.10.0-py3.7.egg/gluoncv/data/video_custom/classification.py", line 197, in __getitem__
    clip_input = self.transform(clip_input)
  File "/home/alfasly/.conda/envs/torch/lib/python3.7/site-packages/mxnet/gluon/block.py", line 693, in __call__
    out = self.forward(*args)
  File "/home/alfasly/.conda/envs/torch/lib/python3.7/site-packages/mxnet/gluon/nn/basic_layers.py", line 55, in forward
    x = block(x)
  File "/home/alfasly/.conda/envs/torch/lib/python3.7/site-packages/mxnet/gluon/block.py", line 693, in __call__
    out = self.forward(*args)
  File "/home/alfasly/.local/lib/python3.7/site-packages/gluoncv-0.10.0-py3.7.egg/gluoncv/data/transforms/video.py", line 520, in forward
    assert th == h or tw == w
AssertionError
"""

where it can be understood that either height or width of the read video must be `224` since `  --input-size 224 \` :
https://github.com/dmlc/gluon-cv/blob/f91e161779515b60e80b2fba5afec55683b3b983/gluoncv/data/transforms/video.py#L492-L540

temporary, I solve this by just modifying these height and width parameters `    --input-size 224 \
    --new-height 224 \
    --new-width 298 \` in shell script
which is different from the script parameters you provided. may you clarify this problem, please.

-------------

2. The second query is about the parameters `--num _segments 10` and  `--three-crop`. Do you use them for all models evaluated, including i3d, 2D, p3d, and r2plus1d ? because I evaluated the 2D model `resnet50_v1b_hmdb51_tsn` which has `--num-segments 3 \` in training but when I test it with `--num _segments 10` and  `--three-crop`, I didn't get the same results.


Thank you in advance.

**Comment by bryanyzhu** [comment]
1. As you can see in 
```
h, w, _ = clips[0].shape 
th, tw = self.size 
assert th == h or tw == w 
```
It requires `--input-size` is equal to either `--new-height` or `--new-width`. Because when you do three-cropping (no matter from left to right, or from top to bottom), you want to make sure the three crops can cover the entire image. This means the crop size has to be equal to at least one dimension of the original image. 

2. I use `--num-segments 10` and `--three-crop` for all 3D models, like I3D, P3D, R2+1D, SlowFast. But I use `-num-segments 25` and `--ten-crop` for 2D models like TSN. Because these are the standard evaluation protocol to evaluate video models.
