### ISSUE TITLE
Tutorial Fine-tuning SOTA video models on your own dataset

### ISSUE THREAD

**Issue by fasttigare** [dmlc/gluon-cv#1607]
Hello
I tried to follow the tutorial using my own dataset (NTU RGDD) dataset with pretrained vgg16_ucf101, I loaded a videos directly but I am facing this error:
 mxnet.base.MXNetError: [13:55:37] C:\Jenkins\workspace\mxnet-tag\mxnet\src\operator\nn\convolution.cc:152: Check failed: dshp.ndim() == 4U (5 vs. 4) : Input data should be 4D in batch-num_filter-y-x

please advice

**Comment by fasttigare** [comment]
I fixed the above error by setting gpu=0, but now getting this error:
  return _nx.concatenate(expanded_arrays, axis=axis, out=out)
MemoryError

**Comment by bryanyzhu** [comment]
It seems you are loading videos directly for training. If this is the case, please specify `video_loader=True` and `use_decord=True` in your VideoClsCustom class. The example in the tutorial is loading video frames for training.

For the dimension mismatch problem, the input should be 4D for 2D CNN models. The shape should be 1x3x224x224, which is a single frame. Please check the input shape to the network, maybe you modify other settings, so that your input is a 5D input.
