### ISSUE TITLE
feature vector size does not change as num-segments increase

### ISSUE THREAD

**Issue by R2D2oid** [dmlc/gluon-cv#1657]
I'm extracting video features using 
`python feat_extract.py --data-list video_list.txt --model i3d_resnet50_v1_kinetics400 --save-dir feats --num-segments 10`

Changing the `num-segments` parameter value does not change the dimensionality of the output feature. Both `--num-segments 1` and `--num-segments 10` result in `1 x 2048` feature dims.

Could someone please verify that this is the expected behavior? I assumed that `--num-segment 10` will divide the input video into 10 shorter clips and extracts the feats separately for each clip; resulting in shape `10 x 2048`  

Here is the line that I'm referring to:
https://github.com/dmlc/gluon-cv/blob/ab03ca04c588342be5cd659c3f96011c0146ac4f/scripts/action-recognition/feat_extract.py#L199

**Comment by bryanyzhu** [comment]
Yes, this is expected behavior. We automatically handle this in model forward by averaging the 10 predictions into 1, because this is what TSN tries to do. That's why no matter how many segments you set, you will end up with 1x2048 feature (one feature per video).

If you want to change this behavior, you can comment out this line

https://github.com/dmlc/gluon-cv/blob/master/gluoncv/model_zoo/action_recognition/i3d_resnet.py#L620

Then you will have the same number of features as you set `num_segments`.
