### ISSUE TITLE
Logging settings issue

### ISSUE THREAD

**Issue by austinmw** [dmlc/gluon-cv#1704]
In the following file:
https://github.com/dmlc/gluon-cv/blob/master/gluoncv/torch/data/gluoncv_motion_dataset/dataset.py#L16

The log is set to the root logger. This makes it very difficult to import from this file and control log settings. Can you please change this to `log = logging.getLogger(__name__)`?

**Comment by vsajip** [comment]
In addition, calling `basicConfig()` in a library module is considered bad practice. `basicConfig()` should only be called from `if __name__ == '__main__':`, i.e. from an application rather than a library. See the Python logging documentation advice [here](https://docs.python.org/3/howto/logging-cookbook.html#adding-handlers-other-than-nullhandler-to-a-logger-in-a-library). This is also advised in other places, e.g. [here](https://docs.python-guide.org/writing/logging/#logging-in-a-library).
