### ISSUE TITLE
unstable training speed for Yolov3 and 280 epoch 

### ISSUE THREAD

**Issue by wshuail** [dmlc/gluon-cv#318]
Hi I want to train my own data with Yolov3 and tried GluonCV.
I found the training speed is quite unstable, from 5 images/second to 40 images/second. I checked the training log from [model_zoo](https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/detection/yolo3_darknet53_coco_train.log), and found the same problem. 

Moreover, it need 280 epoch! This is pretty hard work considering the training speed. 

Why the training speed is so unstable ? Do we have some ways to do some improvement? and also for the 280 epoch? Sorry I don't have enough resources to try ...

Thank you!

**Comment by gachiemchiep** [comment]
@wshuail 

I know this is non-sense but just do the training man. If you use the pre-trained network, you could get the desired accuracy after 10 or 20 epoch.

**Comment by zhreshold** [comment]
If you are using train_yolo3_rand_size.py, it's training shape varies from 320 to 608. That's why the training speed various.
If you want a faster solution, try train_yolo3.py with fixed `data-shape=416` for example. 
Random size training will provide roughly 1% mAP higher than fixed shape training, but you can trade-off between your budget whatsoever.
