### ISSUE TITLE
DeferredInitializationError occurred when running transfer_learning_minc.py with ResNet50_v1(b,c,d)

### ISSUE THREAD

**Issue by goodtogood** [dmlc/gluon-cv#406]
mxnet 1.3  gluoncv 0.3.0 
DeferredInitializationError occurred when running transfer_learning_minc.py using
modle like ResNet50_v1(b,c,d)

> er.py", line 208, in _check_and_get
>     "num_features, etc., for network layers."%(self.name))
> mxnet.gluon.parameter.DeferredInitializationError: Parameter 'resnetv1b0_dense1_
> weight' has not been initialized yet because initialization was deferred. Actual
>  initialization happens during the first forward pass. Please pass one batch of
> data through the network before accessing Parameters. You can also avoid deferre
> d initialization by specifying in_units, num_features, etc., for network layers.
>

**Comment by hetong007** [comment]
For ResNet-(B,C,D), the `nn.Dense` layer is named as `net.fc` instead of `net.output`:

1. ResNet: https://github.com/dmlc/gluon-cv/blob/master/gluoncv/model_zoo/resnet.py#L437
2. ResNet-(B,C,D): https://github.com/dmlc/gluon-cv/blob/master/gluoncv/model_zoo/resnetv1b.py#L194

Modify your code accordingly will eliminate the error.
