### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by ZihaoZhao** [dmlc/gluon-cv#493]
when I try to run "python train_ssd.py --gpus 0 -j 32 --network resnet50_v1 --data-shape 512 --dataset voc --lr 0.001 --lr-decay-epoch 160,200 --lr-decay 0.1 --epochs 240",I got this error,can someone tell why?thank you very much!

**Comment by zhangpzh** [comment]
I also met this problem today (12/4) when I try to run "python train_ssd.py --data-shape=512 --dataset=coco --gpus=6,7".

**Comment by zhangpzh** [comment]
Hello !  

Reason:
This is because with Python, the recursion depth is limited. (1000 by default. just type sys.getrecursionlimit() )
Please refer to this website: http://blog.51cto.com/leyex/1884041

Solution:
Note that such error is thrown by  "~/software/anaconda2/lib/python2.7/site-packages/mxnet/gluon/data/dataloader.py"

So I directly add sys.setrecursionlimit(2000) at the beginning of this file.

Then the training script runs without error.
