### ISSUE TITLE
Only lowercase class names work in VOCDetection.py 

### ISSUE THREAD

**Issue by sharmalakshay93** [dmlc/gluon-cv#609]
Due to this line, only classes with lowercase names in the xml annotation work. If this is by design, can an assertion/exception be raised if `classes` has any class label with an uppercase character? If this is not by design, can this be changed to not work only for lowercase values? Whichever solution is chosen, I'd like to volunteer to take up this issue.

https://github.com/dmlc/gluon-cv/blob/428ee05d7ae4f2955ef00380a1b324b05e6bc80f/gluoncv/data/pascal_voc/detection.py#L106

**Comment by zhreshold** [comment]
By design, I feel it's easier to deal with case insensitive class names, as people may prefer "person" or "Person" case by case. 
Currently user don't need to worry about the spelling in xml files, but I agree with you that we shoudl raise if CLASSES has uppercase names.
Would you like to contribute a PR?

**Comment by sharmalakshay93** [comment]
@zhreshold sure! I'll contribute a PR. Thanks!

**Comment by sharmalakshay93** [comment]
Closing this since its a duplicate of #614
