### ISSUE TITLE
YOLO target generator

### ISSUE THREAD

**Issue by yuzhms** [dmlc/gluon-cv#845]
Could someone explain how yolo generate target using `YOLOV3TargetMerger`, `YOLOV3DynamicTargetGeneratorSimple`,  `YOLOV3PrefetchTargetGenerator`.

What's the definition of DynamicTarget except it's dynamic generated from network.

**Comment by YimianDai** [comment]
1. `YOLOV3PrefetchTargetGenerator`: Only the best match anchor is set to 1, other anchors are set to 0
2. `YOLOV3DynamicTargetGeneratorSimple`: The good enough anchors (> ignore_iou_thresh) are set to -1, others are set to 0.
3. `YOLOV3TargetMerger`: Use `YOLOV3PrefetchTargetGenerator`'s `1`s to override the corresponding values in `YOLOV3DynamicTargetGeneratorSimple`'s values, so that:
    + The best match anchor is set to 1
    + The good enough but not best anchors are set to -1 (not be punished by the loss)
    + the bad anchors (< ignore_iou_thresh) are set to 0

**Comment by LMerCy** [comment]
@YimianDai But why not just do all these in `YOLOV3PrefetchTargetGenerator`？
