### ISSUE TITLE
Unable to use pretrained params on custom ssd 

### ISSUE THREAD

**Issue by sodadi** [dmlc/gluon-cv#897]
Hi,
I trained the model "ssd_512_vgg16_atrous_voc" on a custom dataset with three classes.
the params were saved in "ssd_512_vgg16_atrous_voc_best.params"

##used while training
_net = get_model(net_name, pretrained_base=True) 
train_dataset = gdata.LstDetection('dataset_train.lst', root=os.path.expanduser('.'))
val_dataset = gdata.LstDetection('dataset_val.lst', root=os.path.expanduser('.'))
classes =["a", "b", "c"]
val_metric = VOC07MApMetric(iou_thresh=0.4, class_names=classes)_

But when I try loading the params to the model:

net = model_zoo.get_model('ssd_512_vgg16_atrous_custom', classes=['a','b','c'], pretrained_base=False, ctx=mx.gpu(0))
net.load_parameters("ssd_512_vgg16_atrous_voc_best.params".strip(), ctx=[mx.gpu(0)])

I get the following error:
**AssertionError: Failed loading Parameter 'ssd0_convpredictor0_conv0_weight' from saved params: shape incompatible expected (16, 0, 3, 3) vs saved (84, 512, 3, 3)**

This model was trained on a GPU context on windows 10

Am I doing something wrong?

**Comment by lgov** [comment]
Hi sodadi,

looking at your code snippet it looks like you finetuned the network with the 20+1 VOC classes instead of the 3+1 you want. The '+1' class is the background class.

If you want to load parameters with load_parameters, the network needs to be constructed in exactly the same way as during training. In your get_model call in training you did not provide your target classes list, so the network got trained with the VOC classes.

'ssd0_convpredictor0_conv0_weight' is the bounding box predictor layer, it predicts 4 coordinates per class (per anchor), so has 4 x nr_of_classes x (3x3) x nr_of_channels weights. The weights in your saved file have 84 as first dimension, so 21x4, whereas you expect 16, so 4x4.

You can solve this by either:
- retraining a model with only 3+1 classes.
- loading the weights in a network with 20+1 classes, and then using reset_class with the reuse_weights dictionary to copy over the weights of the first 4 classes.

hth,

Lieven

**Comment by sodadi** [comment]
Hi Lieven,
Thanks for your reply. I tried using reset_classes as it is:
net = get_model("ssd_512_vgg16_atrous_voc", pretrained_base=True)
net.reset_class(classes)

this threw the error:
**Parameter 'ssd1_convpredictor0_conv0_weight' has not been initialized**

_version info:
>>> mx.__version__
'1.5.0'
>>> import gluoncv as gcv
>>> gcv.__version__
'0.4.0'_

then I included the param: reuse_weights: {0:0, 1:0, 2:0}
and I got the same error.


then I tried out a way, mentioned in the comments for the issue: [https://discuss.mxnet.io/t/object-detection-transfer-learning/2477/3](url)

net = get_model("ssd_512_vgg16_atrous_custom", pretrained_base=True, classes=classes, transfer='voc', ctx=[mx.gpu(0)]).
I am not getting any errors while training and loading param file.
