### ISSUE TITLE
change yolo3 anchors

### ISSUE THREAD

**Issue by AndyStrongBoy** [dmlc/gluon-cv#927]
hi, when I use my own data to train yolo3, I want to change the default anchors because these values don't work well. I encounter with some problems:
1. I have no idea if I can change the number os anchors(default 9), if I change the number, do I need change other code except 'anchors = [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]]'
2.It doesn't have external interface to change the default anchors, so when I deploy my project I have to use the source code of gluoncv rather than my own code
If you have some idea ,please let me know, thank you!

**Comment by zhreshold** [comment]
the desired customization model should follow https://github.com/dmlc/gluon-cv/blob/master/gluoncv/model_zoo/yolo/yolo3.py#L918 to build a new yolo network. Directly changing anchors will cause a lot of trouble if not done properly.

Regarding the anchors, it's list of list, default is 3 layers, each layer has [w1, h1, w2, h2, w3, h3], so you can modify it accordingly. Note that since the network has three out tips so you can only have three layers of anchors. To increase layers, you have to modify network as well which is not trivial.

**Comment by AndyStrongBoy** [comment]
Thanks for your reply.
