### ISSUE TITLE
get_im_aspect_ratio() is only implemented for COCO

### ISSUE THREAD

**Issue by ifeherva** [dmlc/gluon-cv#949]
I am trying to run the faster-rcnn training script on anything other than COCO but I get a crash since my dataset does not implement get_im_aspect_ratio() needed by SplitSortedBucketSampler.

Is there a quick way to fix this? My dataset is huge and I would prefer not loading each image to  precompute this.

**Comment by zhreshold** [comment]
@Jerryzcn Is the new PR breaking other datasets?

**Comment by zhreshold** [comment]
Actually by providing `[1] * len(train_dataset)` instead of `train_dataset.get_im_aspect_ratio()` can solve the NotImplemented problem

**Comment by Jerryzcn** [comment]
You can use the default sampler instead of the SplitSortedBucketSampler. However, using this approach will decrease your training performance quite a bit. Our COCO load's default behavior is actually calculating the aspect ratio from the json file instead of reading the image. Does you json file have img height and width info?

**Comment by ifeherva** [comment]
No, I have a RecordFileDetection() as per https://gluon-cv.mxnet.io/build/examples_datasets/detection_custom.html
