### ISSUE TITLE
Weight initialization in FeatureExpander of SSD

### ISSUE THREAD

**Issue by yuewu001** [dmlc/gluon-cv#96]
The SSD algorithm uses the following initialization method for symbolic network:

```
weight_init = mx.init.Xavier(rnd_type='gaussian', factor_type='out', magnitude=2)
for i, f in enumerate(num_filters):
       if use_1x1_transition:
            num_trans = max(min_depth, int(round(f * reduce_ratio)))
            y = mx.sym.Convolution(
            y, num_filter=num_trans, kernel=(1, 1), no_bias=use_bn,
                    name='expand_trans_conv{}'.format(i), attr={'__init__': weight_init})
```
However, the SymbolBlock does not get the attr when creating parameters as follows:

```
for i in out.list_arguments():
        if i not in input_names:
            self.params.get(i, allow_deferred_init=True)

for i in out.list_auxiliary_states():
       if i not in input_names:
            self.params.get(i, grad_req='null', allow_deferred_init=True)
```
I also found such kind of initialization does not work in my own program. Did I misunderstand the process or are there any other tricks?

**Comment by zhreshold** [comment]
```python
for i in out.list_arguments():
        if i not in input_names:
            self.params.get(i, allow_deferred_init=True)
```
If `out` is a symbol, I assume `self.params` is a gluon.ParameterDict?
Why would you want to mix them this way?

**Comment by yuewu001** [comment]
This comes from the example code of GluonCV:
https://github.com/dmlc/gluon-cv/blob/master/gluoncv/nn/feature.py#L91

Actually, we often need to get the internal feature maps as in the implementation of SSD.  In the gluon interface, I found this is quite hard by following the steps:

1. We need to first convert a Block to Symbol
2. then we use the get_internals() function
3. After that we convert Group the symbols and convert to a SymbolBlock

It seems that we can also get the internal block directly. But we can only get by index but not name.

**Comment by zhreshold** [comment]
The symbolBlock is only required when you want to extract intermediate feature map which you only know the name. 
Gluon can have ``weight_initializer`` support for example https://mxnet.incubator.apache.org/api/python/gluon/nn.html?highlight=conv2d#mxnet.gluon.nn.Conv2D 

So suppose you are building your network in gluon from scratch, you don't need to bother symbol part.

**Comment by yuewu001** [comment]
The problem here is that I want to extract intermediate feature map from a gluon block. Are there any convenient methods like by names as in the Symbol interface?

**Comment by zhreshold** [comment]
You can use slicing if you know the index of the layer.

```python
from mxnet import gluon

net = gluon.model_zoo.vision.get_model('resnet18_v1')
feat1 = net.features[:-2]
print(feat1)
```

**Comment by yuewu001** [comment]
That's the pain point. Index is not convenient. 

Another problem is, whether Gluoncv provides The correct ssd code? It uses the mixed initialization method of symbol and gluon as mentioned aboce.

**Comment by ptrendx** [comment]
Hi @zhreshold, we just hit this issue (and it is actually an issue, not a question :-P ). The code that sets the intiializer in the GluonCV's SSD FeatureExpander here: https://github.com/dmlc/gluon-cv/blob/master/gluoncv/nn/feature.py#L144 and here: https://github.com/dmlc/gluon-cv/blob/master/gluoncv/nn/feature.py#L150 does not actually do anything and you end up with the default initializer (which is `mx.init.Uniform`).

Actually also FYI @Jerryzcn since FPN feature expander also uses `SymbolBlock` with the same not working scheme.

There are 2 problems here:
 - you set the `__init__` attribute on the Convolution and not on the actual weight and bias
 - the SymbolBlock ignores that anyway and makes a `Parameter` without looking at the `__init__` attribute on the `Variable`: https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/gluon/block.py#L1349

**Comment by zhreshold** [comment]
I feel it's time to make the transition to go away from symbolic to pure gluon.
I will do a survey on workloads to rewrite the `FeatureExpander`
