### ISSUE TITLE
How to do semantic segmentation(FCN) with multiple model?

### ISSUE THREAD

**Issue by dnjfk2003** [dmlc/gluon-cv#966]
First, I am not good at understanding AI model, but just follow the guide and use it.

I have a computer with two GPUs and made a FCN model with my own trainset.
When training I change the code to "ctx_list = [mx.gpu(0), mx.gpu(1)]" from train.py. 
And I checked two GPUs is working on training.
But the problem is when I predict new picture, the model only use single GPU.
I don't know where I should modify on code(demo_fcn.py)

this is my code
###############################

modelFile = 'MYOWNMODEL.params'
ctx = mx.gpu()
## get pre-trained model
model = gluoncv.model_zoo.get_fcn(dataset='pascal_voc', backbone='resnet50', retrained=False)
model.load_parameters(modelFile, ctx = ctx)

img_origin = image.imread('NEW_IMAGE.png')

## normalize the image using dataset mean
transform_fn = transforms.Compose([transforms.ToTensor(),
    transforms.Normalize([.485, .456, .406], [.229, .224, .225])])
img = transform_fn(img_origin)
img = img.expand_dims(0).as_in_context(ctx)
  
output = model.demo(img)
#####################################

when I modified code from 'ctx = mx.gpu()' to 'ctx = [mx.gpu(0), mx.gpu(1)]', an error occurred at "img = img.expand_dims(0).as_in_context(ctx)"
( Failed to load Parameter 'fcn1_resnetv1s_conv0_weight' on [gpu(0), gpu(1)] because it was previous initialized on [gpu(0)].)

is there anyone who can advise me?
Thank you.

**Comment by bryanyzhu** [comment]
Hi, the problem is at when loading the weights, not at "img = img.expand_dims(0).as_in_context(ctx)".

If you want to use multiple gpus, please reset context before loading the weights. For example, 

```
modelFile = 'MYOWNMODEL.params'
ctx = [mx.gpu(0), mx.gpu(1)]
model = gluoncv.model_zoo.get_fcn(dataset='pascal_voc', backbone='resnet50', retrained=False)
model.collect_params().reset_ctx(ctx=ctx)
model.load_parameters(modelFile, ctx=ctx)
```

This should work. 

However, `as_in_context(ctx)` function only accept single gpu context because there is only one copy of data. If you have more data and wants to spread out on multiple gpus, please consider use [`split_and_load`](https://beta.mxnet.io/api/gluon/_autogen/mxnet.gluon.utils.split_and_load.html).
